name: Build Android APK

on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      # =========================
      # 1. Checkout
      # =========================
      - name: Checkout
        uses: actions/checkout@v4

      # =========================
      # 2. Java
      # =========================
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '17'
          cache: gradle

      # =========================
      # 3. Flutter
      # =========================
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.x'
          channel: stable
          cache: true

      # =========================
      # 4. Restore Android Keystore
      # =========================
      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > "$GITHUB_WORKSPACE/release.jks"

      # =========================
      # 5. Create key.properties
      # =========================
      - name: Create key.properties
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          cat > simple_live_app/android/key.properties <<EOF
          storePassword=$KEYSTORE_PASSWORD
          keyPassword=$KEY_PASSWORD
          keyAlias=$KEY_ALIAS
          storeFile=$GITHUB_WORKSPACE/release.jks
          EOF

      # =========================
      # 6. Flutter Pub Get
      # =========================
      - name: Flutter Pub Get
        working-directory: simple_live_app
        run: flutter pub get

      # =========================
      # 7. Build Signed APK
      # =========================
      - name: Build APK
        working-directory: simple_live_app
        run: flutter build apk --release --split-per-abi

      # =========================
      # 8. Upload APK
      # =========================
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: simple_live_app/build/app/outputs/flutter-apk/*.apk
